services:
  php:
    build: ./docker
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
    ports:
      - target: 80
        published: 8080
    environment:
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=laravel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/json
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - target: 16686
        published: 16686 
      # grpc
      # - target: 4317
      #   published: 4317
      - target: 4318
        published: 4318
  mysql:
    image: mysql
    ports:
      - target: 3306
        published: 3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=true